openapi: 3.0.0
info:
  title: XLSX Max API
  description: API для нахождения N-го максимального числа в файле XLSX.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Локальный сервер

tags:
  - name: Xlsx

paths:
  /api/xlsx/find-nth-max:
    post:
      tags: [ Xlsx ]
      operationId: findNthMax
      summary: Найти N-й максимум
      description: Принимает файл XLSX и число N, возвращает N-е максимальное число из файла.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Файл XLSX
                n:
                  type: integer
                  description: Позиция максимального числа
                  example: 3
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: integer
                example: 42
        '4XX':
          $ref: '#/components/schemas/ApiErrorResponse'
        '5XX':
          $ref: '#/components/schemas/ApiErrorResponse'

components:
  schemas:
    ApiErrorResponse:
      type: object
      description: Схема ответа на ошибки клиента
      required:
        - message
      properties:
        message:
          type: string
          example: Ошибка обработки запроса
          description: Текст ошибки
